config/routes.rb
Rails.application.routes.draw do
  post '/chatbot', to: 'media#chatbot'

  get '/discover', to: 'media#index', as: 'discover'

  get '/dashboard', to: 'users#show', as: 'dashboard'
  devise_for :users

  scope :bot do
    post 'send', to: 'bot#send_message', as: :bot_send
  end

  root to: 'pages#home'

  resources :media, only: [] do
    resources :libraries, only: [:create]
    resources :reviews, only: [:create]
  end

  resources :categories, only: [] do
    resources :preference_categories, only: [:create, :destroy]
  end

  resources :moods, only: [] do
    resources :preference_moods, only: [:create, :destroy]
  end

  resources :topics, only: [:index, :create, :show, :destroy]
  resources :comments, only: [:create, :destroy]
end

app/models/actor.rb
class Actor < ApplicationRecord
  validates :first_name, presence: true, uniqueness: { scope: :last_name }
  validates :last_name, presence: true
  has_many :media_actors
  has_many :media, through: :media_actors

  def full_name
    first_name << ' ' << last_name
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  validates :name, presence: true, uniqueness: true
  has_many :media_categories
  has_many :media, through: :media_categories
end

app/models/chiengeant.rb
class Chiengeant < ApplicationRecord
  validates :data, presence: true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :topic
  belongs_to :user

  validates :content, presence: true
  validates :topic, presence: true
  validates :user, presence: true
end

app/models/director.rb
class Director < ApplicationRecord
  validates :first_name, presence: true, uniqueness: { scope: :last_name }
  validates :last_name, presence: true
  has_many :media_directors
  has_many :media, through: :media_directors

  def full_name
    first_name << ' ' << last_name
  end
end

app/models/library.rb
class Library < ApplicationRecord
  belongs_to :user
  belongs_to :medium
  validates :seen, default: false
end

app/models/media_actor.rb
class MediaActor < ApplicationRecord
  belongs_to :medium
  belongs_to :actor
end

app/models/media_category.rb
class MediaCategory < ApplicationRecord
  belongs_to :medium
  belongs_to :category
end

app/models/media_director.rb
class MediaDirector < ApplicationRecord
  belongs_to :medium
  belongs_to :director
end

app/models/media_mood.rb
class MediaMood < ApplicationRecord
  belongs_to :medium
  belongs_to :mood
end

app/models/medium.rb
class Medium < ApplicationRecord
  belongs_to :studio
  has_many :libraries
  has_many :reviews
  has_many :users, through: :libraries
  has_many :media_actors
  has_many :media_directors
  has_many :media_moods
  has_many :media_categories
  has_many :actors, through: :media_actors
  has_many :directors, through: :media_directors
  has_many :moods, through: :media_moods
  has_many :categories, through: :media_categories
  validates :title, presence: true
  validates :synopsys, presence: true
  validates :duration, presence: true
  validates :press_rating, presence: true
  validates :audience_rating, presence: true

  include PgSearch
  pg_search_scope :search_in_all,
    against: [:title, :synopsys, :duration, :year, :country],
    associated_against: {
      categories: [:name],
      moods: [:name],
      directors: [:first_name, :last_name],
      actors: [:first_name, :last_name],
      studio: [:name]
    },
    using: {
      tsearch: { prefix: true } # <-- now `superman batm` will return something!
    }
end

app/models/mood.rb
class Mood < ApplicationRecord
  validates :name, presence: true, uniqueness: true
  has_many :media_moods
  has_many :media, through: :media_moods
end

app/models/preference_mood.rb
class PreferenceMood < ApplicationRecord
  belongs_to :user
  belongs_to :mood
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :medium
  belongs_to :user
  validates :title, presence: true
  validates :description, presence: true
end

app/models/store.rb
class Store < ApplicationRecord
  validates :store, presence: true
end

app/models/studio.rb
class Studio < ApplicationRecord
  has_many :media
  validates :name, presence:true, uniqueness: true
end

app/models/topic.rb
class Topic < ApplicationRecord
  belongs_to :user

  validates :title, presence: true, uniqueness: true
  validates :user, presence: true
end

app/models/user.rb
class User < ApplicationRecord
    mount_uploader :photo, PhotoUploader

    validates :email, presence: true
    validates :password, presence: true
    validates :alias, presence: true
    has_many :reviews
    has_many :libraries
    has_many :media, through: :libraries
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

    has_many :topics
    has_many :comments
end

app/controllers/bot_controller.rb
require 'recastai'

class BotController < ActionController::Base
  skip_before_action :verify_authenticity_token

  def send_message
    client = RecastAI::Client.new("7390b5ef0c620284e447c95d5da1060a")
    request = RecastAI::Request.new("7390b5ef0c620284e447c95d5da1060a")
    build = RecastAI::Build.new("7390b5ef0c620284e447c95d5da1060a")
    # client.request.analyse_text('Hi')
    # connect = client.connect

    res = build.dialog({type: "text", content: params[:message][:content]}, params[:conversation_id])

    render json: { response: res }
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @media_count = media_count
    @time_spent = time_spent
    @average_duration = average_duration
    @favorite_category = favorite('categories')
    @favorite_actor = favorite('actors')
    @favorite_director = favorite('directors')
    @favorite_studio = favorite('studio')
  end

  private

  def user_params
    params.require(:article).permit(:alias, :email, :photo)
  end

  def media_count
    return Library.all.where(already_watched: true, user: current_user).count
  end

  def time_spent
    count = 0
    Library.all.where(already_watched: true, user: current_user).each do |instance|
      count += instance.medium.duration
    end
    return count
  end

  def average_duration
    avg_duration = 0
    total_duration = 0
    Library.all.where(already_watched: true, user: current_user).each do |instance|
      total_duration += instance.medium.duration
      avg_duration = total_duration / media_count
    end
    return avg_duration
  end

  def favorite(type)
    if Library.all.where(already_watched: true, user: current_user) == []
      return 0
    else
      name_tab = Library.all.where(already_watched: true, user: current_user).map do |instance|
        if type == 'categories'
          instance.medium.send(type.to_sym).map { |element| element.name }
        elsif type == 'actors' || type == 'directors'
          instance.medium.send(type.to_sym).map { |element| element.full_name }
         else
          instance.medium.send(type.to_sym).name
        end
      end
      name_uniq = name_tab.flatten.uniq
      name_count = name_uniq.map do |occurence|
        name_tab.flatten.count(occurence)
      end
      value_max = name_count.each_with_index.max[1]
      return name_uniq[value_max]
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/users/show.html.erb
<div class="banner" style="background-image: radial-gradient(rgba(0,0,0,0.4), rgba(0,0,0,0.4)),url('<%= image_path 'background-cinema.jpg' %>');">
  <div class="container">
    <br><br>
    <div class="background-preference">
      <div class="tab in-line">
        <ul class="nav nav-tabs" role="tablist">
          <li id="preferences-title" role="presentation" class="active"><a id="preferences-title-design"  class="tab" href="#preferences" aria-controls="preferences" role="tab" data-toggle="tab">PREFERENCES</a></li>
          <li id="already_watched-title" role="presentation"><a id="already_watched-title-design"  class="tab" href="#already_watched" aria-controls="already_watched" role="tab" data-toggle="tab">ALREADY WATCH</a></li>
          <li id="watch-later-title" role="presentation"><a id="watch-later-title-design" class="tab"  href="#watch-later" aria-controls="watch-later" role="tab" data-toggle="tab">WATCH LATER</a></li>
          <li id="blacklist-title" role="presentation"><a id="blacklist-title-design"  class="tab" href="#blacklist" aria-controls="blacklist" role="tab" data-toggle="tab">BLACKLIST</a></li>
          <li id="profile-title" role="presentation"><a id="profile-title-design"  class="tab" href="#profile" aria-controls="profile" role="tab" data-toggle="tab">PROFILE</a></li>
        </ul>
      </div>
      <div class="tab-content">
        <div role="tabpanel" class="tab-pane active" id="preferences">
          <div>
            <br>
            <h4>Categories : </h4>
            <div class="btn-group">
              <button type="button" class="btn btn-danger dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Add preferences <span class="caret"></span></button>
              <ul class="dropdown-menu">
                <% Category.all.each do |instance| %>
                <li><%= link_to instance.name, category_preference_categories_path(instance.id), method: :post %></li>
                <li role="separator" class="divider"></li>
                <% end %>
              </ul>
            </div><br><br>
            <%= render 'components/preference_category' %>
          </div><br>
          <div>
            <h4>Moods : </h4>
            <div class="btn-group">
              <button type="button" class="btn btn-danger dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Add preferences <span class="caret"></span></button>
              <ul class="dropdown-menu">
                <% Mood.all.each do |instance| %>
                <li><%= link_to instance.name, mood_preference_moods_path(instance.id), method: :post %></li>
                <li role="separator" class="divider"></li>
                <% end %>
              </ul>
            </div><br><br>
            <%= render 'components/preference_mood' %>
          </div><br>
<!--           <h4>Duration wanted : </h4>
          <label for="adv[duration]"></label>
          <div class="range-size">
            <input type="range" name="adv[duration]" value="90" min="0" max="300" oninput="adv[duration].value" step="10" >
          </div> -->
        </div>
        <div role="tabpanel" class="tab-pane" id="already_watched">
          <div class="container">
            <div class="row">
              <% Library.all.where(already_watched: true, user: current_user).each do |instance| %>
              <div class="col-xs-12 col-sm-3">
                <%= render 'components/card_dashboard', medium: instance.medium %>
              </div>
              <% end %>
            </div>
          </div>
          <br>
        </div>
        <div role="tabpanel" class="tab-pane" id="watch-later">
          <div class="container">
            <div class="row">
              <% Library.all.where(watch_later: true, user: current_user).each do |instance| %>
              <div class="col-xs-12 col-sm-3">
                <%= render 'components/card_dashboard', medium: instance.medium %>
              </div>
              <% end %>
            </div>
          </div>
          <br>
        </div>
        <div role="tabpanel" class="tab-pane" id="blacklist">
          <div class="">
            <div class="row">
              <% Library.all.where(blacklist: true, user: current_user).each do |instance| %>
              <div class="col-xs-12 col-sm-6 col-md-4 col-lg-3">
                <%= render 'components/card_dashboard', medium: instance.medium %>
              </div>
              <% end %>
            </div>
          </div>
          <br>
        </div>
        <div role="tabpanel" class="tab-pane" id="profile">
          <div class="container">
          </div>
          <div>
              <div class="row">
                <div class="col-xs-4 metric-set">
                  <br><br>
              <p>Alias:</p>
              <p>Email:</p> <br>
                </div>
               <div class="col-xs-2 metric-set details-metric-text">
                 <br><br>
              <p><%= current_user.alias %></p>
              <p><%= current_user.email %></p> <br>
               </div>
                <div class="col-xs-6 photo-profile">
                  <br>
                  <%= cl_image_tag(current_user.photo, width: 100, height: 100, crop: :thumb, gravity: :face)  %>
                </div>
            </div>
            <div class="line"></div>
              <div class="row">
                <div class="col-xs-4 metric-set">
                  <br>
                  <p>Number of content already watched : </p>
                  <p>Time spent watching contents :</p>
                  <p>Average duration of thoses contents :</p>
                  <p>Favorite category :</p>
                  <p>Favorite actor :</p>
                  <p>Favorite director :</p>
                  <p>Favorite studio :</p>
                </div>
               <div class="col-xs-8 metric-set details-metric-text">
                 <br>
                 <p><%= @media_count %></p>
                 <p><%= @time_spent %></p>
                 <p><%= @average_duration %></p>
                 <p><%= @favorite_category %></p>
                 <p><%= @favorite_actor %></p>
                 <p><%= @favorite_director %></p>
                 <p><%= @favorite_studio %></p>
               </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<div class="background-rest"></div>