config/routes.rb
Rails.application.routes.draw do
  post '/chatbot', to: 'media#chatbot'

  get '/discover', to: 'media#index', as: 'discover'

  get '/dashboard', to: 'users#show', as: 'dashboard'
  devise_for :users

  scope :bot do
    post 'send', to: 'bot#send_message', as: :bot_send
  end

  root to: 'pages#home'

  resources :media, only: [] do
    resources :libraries, only: [:create]
    resources :reviews, only: [:create]
  end

  resources :categories, only: [] do
    resources :preference_categories, only: [:create, :destroy]
  end

  resources :moods, only: [] do
    resources :preference_moods, only: [:create, :destroy]
  end

  resources :topics, only: [:index, :create, :show, :destroy]
  resources :comments, only: [:create, :destroy]
end

app/models/actor.rb
class Actor < ApplicationRecord
  validates :first_name, presence: true, uniqueness: { scope: :last_name }
  validates :last_name, presence: true
  has_many :media_actors
  has_many :media, through: :media_actors

  def full_name
    first_name << ' ' << last_name
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  validates :name, presence: true, uniqueness: true
  has_many :media_categories
  has_many :media, through: :media_categories
end

app/models/chiengeant.rb
class Chiengeant < ApplicationRecord
  validates :data, presence: true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :topic
  belongs_to :user

  validates :content, presence: true
  validates :topic, presence: true
  validates :user, presence: true
end

app/models/director.rb
class Director < ApplicationRecord
  validates :first_name, presence: true, uniqueness: { scope: :last_name }
  validates :last_name, presence: true
  has_many :media_directors
  has_many :media, through: :media_directors

  def full_name
    first_name << ' ' << last_name
  end
end

app/models/library.rb
class Library < ApplicationRecord
  belongs_to :user
  belongs_to :medium
  validates :seen, default: false
end

app/models/media_actor.rb
class MediaActor < ApplicationRecord
  belongs_to :medium
  belongs_to :actor
end

app/models/media_category.rb
class MediaCategory < ApplicationRecord
  belongs_to :medium
  belongs_to :category
end

app/models/media_director.rb
class MediaDirector < ApplicationRecord
  belongs_to :medium
  belongs_to :director
end

app/models/media_mood.rb
class MediaMood < ApplicationRecord
  belongs_to :medium
  belongs_to :mood
end

app/models/medium.rb
class Medium < ApplicationRecord
  belongs_to :studio
  has_many :libraries
  has_many :reviews
  has_many :users, through: :libraries
  has_many :media_actors
  has_many :media_directors
  has_many :media_moods
  has_many :media_categories
  has_many :actors, through: :media_actors
  has_many :directors, through: :media_directors
  has_many :moods, through: :media_moods
  has_many :categories, through: :media_categories
  validates :title, presence: true
  validates :synopsys, presence: true
  validates :duration, presence: true
  validates :press_rating, presence: true
  validates :audience_rating, presence: true

  include PgSearch
  pg_search_scope :search_in_all,
    against: [:title, :synopsys, :duration, :year, :country],
    associated_against: {
      categories: [:name],
      moods: [:name],
      directors: [:first_name, :last_name],
      actors: [:first_name, :last_name],
      studio: [:name]
    },
    using: {
      tsearch: { prefix: true } # <-- now `superman batm` will return something!
    }
end

app/models/mood.rb
class Mood < ApplicationRecord
  validates :name, presence: true, uniqueness: true
  has_many :media_moods
  has_many :media, through: :media_moods
end

app/models/preference_mood.rb
class PreferenceMood < ApplicationRecord
  belongs_to :user
  belongs_to :mood
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :medium
  belongs_to :user
  validates :title, presence: true
  validates :description, presence: true
end

app/models/store.rb
class Store < ApplicationRecord
  validates :store, presence: true
end

app/models/studio.rb
class Studio < ApplicationRecord
  has_many :media
  validates :name, presence:true, uniqueness: true
end

app/models/topic.rb
class Topic < ApplicationRecord
  belongs_to :user

  validates :title, presence: true, uniqueness: true
  validates :user, presence: true
end

app/models/user.rb
class User < ApplicationRecord
    mount_uploader :photo, PhotoUploader

    validates :email, presence: true
    validates :password, presence: true
    validates :alias, presence: true
    has_many :reviews
    has_many :libraries
    has_many :media, through: :libraries
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

    has_many :topics
    has_many :comments
end

app/controllers/bot_controller.rb
require 'recastai'

class BotController < ActionController::Base
  skip_before_action :verify_authenticity_token

  def send_message
    client = RecastAI::Client.new("7390b5ef0c620284e447c95d5da1060a")
    request = RecastAI::Request.new("7390b5ef0c620284e447c95d5da1060a")
    build = RecastAI::Build.new("7390b5ef0c620284e447c95d5da1060a")
    # client.request.analyse_text('Hi')
    # connect = client.connect

    res = build.dialog({type: "text", content: params[:message][:content]}, params[:conversation_id])

    render json: { response: res }
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Agora</title>
    <link href="https://fonts.googleapis.com/css?family=Permanent+Marker" rel="stylesheet">
    <link rel="icon" type="image/png" href="https://png.icons8.com/metro/1600/cinema.png">
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body class="<%= params[:controller] %> <%= params[:action] %>">
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <%= yield %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>

    <script>

      /* Light YouTube Embeds by @labnol */
      /* Web: http://labnol.org/?p=27941 */

      document.addEventListener("DOMContentLoaded",
          function() {
              var div, n,
                  v = document.getElementsByClassName("youtube-player");
              for (n = 0; n < v.length; n++) {
                  div = document.createElement("div");
                  div.setAttribute("data-id", v[n].dataset.id);
                  div.innerHTML = labnolThumb(v[n].dataset.id);
                  div.onclick = labnolIframe;
                  v[n].appendChild(div);
              }
          });

      function labnolThumb(id) {
          var thumb = '<img src="https://i.ytimg.com/vi/ID/hqdefault.jpg">',
              play = '<div class="play"></div>';
          return thumb.replace("ID", id) + play;
      }

      function labnolIframe() {
          var iframe = document.createElement("iframe");
          var embed = "https://www.youtube.com/embed/ID?controls=1&showinfo=0&rel=0&autoplay=1&loop=1&showinfo=0&autohide=1";
          iframe.setAttribute("src", embed.replace("ID", this.dataset.id));
          iframe.setAttribute("frameborder", "0");
          iframe.setAttribute("allowfullscreen", "1");
          this.parentNode.replaceChild(iframe, this);
        }

    </script>
  </body>
</html>

app/views/layouts/home.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Agora</title>
    <link href="https://fonts.googleapis.com/css?family=Permanent+Marker" rel="stylesheet">
    <link rel="icon" type="image/png" href="https://png.icons8.com/metro/1600/cinema.png">
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= stylesheet_pack_tag 'hello_vue' %>
    <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body>
    <%= render 'shared/navbar-home' %>
    <%= render 'shared/flashes' %>
    <%= yield %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
    <%= javascript_pack_tag 'hello_vue' %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="banner" style="background-image: radial-gradient(rgba(0,0,0,0.1), rgba(0,0,0,0.1)),url('<%= image_path 'redseat.jpg' %>');">
  <div class="banner-content">
    <div>
      <%= image_tag "logo.png", height: 150 %>

      <div id="vue-bot"></div>
    </div>
  </div>
</div>

<br><br>
<div class="container">
  <div class="row icon-home">
    <div class="col-sm-4">
      <div class='text-center'>
        <i class="fas fa-stopwatch"></i>
      </div><br>
      <p>Vous en avez marre de mettre des heures à chercher du contenu? En quelques clics, chacun peut trouver son bonheur ou du moins un bon film !</p>
    </div>
    <div class="col-sm-4">
      <p>Nous proposons un contenu adapté à chaque spectateur. Vous pouvez ajouter vos préférences ou envies du moment et vous laisser guider vers le contenu qui vous correspond !</p><br>
      <div class='text-center'>
        <i class="fas fa-pencil-alt"></i>
      </div>
    </div>
    <div class="col-sm-4">
      <div class='text-center'>
        <i class="far fa-comments"></i>
      </div><br>
      <p>Mais c'est plus que ça, vous pourrez intégrer cette belle communauté qu'est l'AGORA club afin d'échanger vos avis, noter les contenus, gérer votre cinémathèque et plein d'autres fonctionnalités !</p>
    </div>
  </div>
</div>
<br><br>



<script>
  element = document.getElementById('adv-search')
  if (element) {
      element.addEventListener('click', (event) => {
        hidiv = (document.getElementsByClassName('adv-search')[0])
        hidiv.hidden = !hidiv.hidden
      });
  }
</script>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar-home.html.erb
<div class="navbar-agora">
  <!-- Logo -->


<div class="navbar-search">
<!--   search -->

</div>

  <!-- Right Navigation -->
  <div class="navbar-agora-right hidden-xs hidden-sm">

    <% if user_signed_in? %>

      <!-- Avatar with dropdown menu -->
      <div class="navbar-agora-item">
        <div class="dropdown">
        <% if current_user.nil? || current_user.photo.blank? %>
        <%= image_tag "blank-avatar.png", class: "avatar dropdown-toggle", id: "navbar-agora-menu", data: {toggle: "dropdown"}  %>
        <% else %>
        <%= cl_image_tag current_user.photo, class: "avatar dropdown-toggle", id: "navbar-agora-menu", data: {toggle: "dropdown"}  %>
        <% end %>
          <ul class="dropdown-menu dropdown-menu-right navbar-agora-dropdown-menu">
            <li>
              <%= link_to dashboard_path do %>
                 <i class="fa fa-user"></i> <%= t(".profile", default: "Film library") %>
              <% end %>
            </li>
            <li>
              <%= link_to dashboard_path do %>
                <i class="fa fa-cog"></i>  <%= t(".settings", default: "Preferences") %>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out-alt"></i>  <%= t(".sign_out", default: "Log out") %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>
    <% else %>
      <!-- Login link (when logged out) -->
      <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-agora-item navbar-agora-link" %>
    <% end %>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-agora-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-agora-dropdown-menu">
        <li><a href="#">Some mobile link</a></li>
        <li><a href="#">Other one</a></li>
        <li><a href="#">Other one</a></li>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar-agora">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-agora-brand" do %>
    <%= image_tag "logo.png", height: 80 %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-agora-right hidden-xs hidden-sm">

    <% if user_signed_in? %>

      <!-- Avatar with dropdown menu -->
      <div class="navbar-agora-item">
        <div class="dropdown">
        <% if current_user.nil? || current_user.photo.blank? %>
        <%= image_tag "blank-avatar.png", class: "avatar dropdown-toggle", id: "navbar-agora-menu", data: {toggle: "dropdown"}  %>
        <% else %>
        <%= cl_image_tag current_user.photo, class: "avatar dropdown-toggle", id: "navbar-agora-menu", data: {toggle: "dropdown"}  %>
        <% end %>
          <ul class="dropdown-menu dropdown-menu-right navbar-agora-dropdown-menu">
            <li>
              <%= link_to dashboard_path do %>
                 <i class="fa fa-user"></i> <%= t(".profile", default: "Film library") %>
              <% end %>
            </li>
            <li>
              <%= link_to dashboard_path do %>
                <i class="fa fa-cog"></i>  <%= t(".settings", default: "Preferences") %>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out-alt"></i>  <%= t(".sign_out", default: "Log out") %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>
    <% else %>
      <!-- Login link (when logged out) -->
      <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-agora-item navbar-agora-link" %>
    <% end %>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-agora-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-agora-dropdown-menu">
        <li><a href="#">Some mobile link</a></li>
        <li><a href="#">Other one</a></li>
        <li><a href="#">Other one</a></li>
      </ul>
    </div>
  </div>
</div>