config/routes.rb
Rails.application.routes.draw do
  post '/chatbot', to: 'media#chatbot'

  get '/discover', to: 'media#index', as: 'discover'

  get '/dashboard', to: 'users#show', as: 'dashboard'
  devise_for :users

  scope :bot do
    post 'send', to: 'bot#send_message', as: :bot_send
  end

  root to: 'pages#home'

  resources :media, only: [] do
    resources :libraries, only: [:create]
    resources :reviews, only: [:create]
  end

  resources :categories, only: [] do
    resources :preference_categories, only: [:create, :destroy]
  end

  resources :moods, only: [] do
    resources :preference_moods, only: [:create, :destroy]
  end

  resources :topics, only: [:index, :create, :show, :destroy]
  resources :comments, only: [:create, :destroy]
end

app/controllers/media_controller.rb
require 'services/tmdb_api_service'
require 'pp'

class MediaController < ApplicationController
  skip_before_action :authenticate_user!
  skip_before_action :verify_authenticity_token, only: [:chatbot]

  def index
    if params[:nb].blank?
      @nb = 0
    else
      @nb = params['nb'].to_i
    end
    # @medium = Medium.find(session[:media][@nb])
    @data = Chiengeant.all.first.data[1...-1].split(',').map(&:to_i)
    @medium = Medium.find(@data[@nb])
  end

  def chatbot
    # session.delete(:media)
    Chiengeant.destroy_all unless Chiengeant.all.blank?

    data = JSON.parse(request.body.read)['conversation']['memory']

    p "DATA: " + data.inspect,

    if data.has_key? 'movie'
      title_search = TmdbApiService.new(data['movie']['raw']).search_movie
    end

    if data.has_key? 'genre'
      genre_search = TmdbApiService.new(data['genre']['raw']).sort_by_genre
    end

    if data.has_key? 'person'
      person_search = TmdbApiService.new(data['person']['raw']).search_person
    end

    movies = (title_search || [] + genre_search || [] + person_search || []).compact

    movies_count = movies.uniq.map do |movie|
      movies.count(movie)
    end

    movies_sorted = movies.group_by{|x| x}.sort_by{|k, v| -v.size}.map(&:first)

    # session[:media] = fetch_to_database(movies_sorted).map { |m| m.id }.compact
    media = fetch_to_database(movies_sorted).map { |m| m.id }.compact
    Chiengeant.create(data: media)


    render json: {
      replies: [{ type: 'text', content: 'Roger that' }],
    }
  end

  private

  # def json_request?
  #   p request.body
  #   p request.format.json?
  # end

  def search_media
    session.delete(:media)
    if !params[:q].blank? && !advanced_search?
      session[:media] = simple_search_api.map { |m| m.id }.compact
    elsif advanced_search?
      session[:media] = advanced_search_api.map { |m| m.id }.compact
    else
      session[:media] = Medium.all.first(500).map { |m| m.id }
    end
  end

  def simple_search_api
    results = TmdbApiService.search(params[:q])
    fetch_to_database(results[:movie].uniq)
  end

  def advanced_search_api
    base_poster_url = 'http://image.tmdb.org/t/p/w500/'

    query_sort = TmdbApiService.search(params[:q])[:movie] unless params[:q].blank?
    category_sort = TmdbApiService.new(params[:adv]).sort_by_genre unless params[:adv][:c].blank?
    actor_sort = TmdbApiService.new(params[:adv]).sort_by_actor unless params[:adv][:a].blank?
    director_sort = TmdbApiService.new(params[:adv]).sort_by_director unless params[:adv][:d].blank?

    result = ((query_sort || []) + (category_sort || []) + (actor_sort || []) + (director_sort || [])).uniq
    fetch_to_database(result)
  end

  def fetch_to_database(result)
    media = []
    result.each do |movie|
      medium_found = Medium.find_by(title: movie['title'])
      detail_movie = TmdbApiService.call_movie(movie['id'])
      if medium_found
        medium = medium_found
      else
        medium = store_in_database(detail_movie)
      end
      media << medium
    end
    return media
  end

  def update_database(medium, movie)
    studio = find_studio(movie)

    medium.update(
      poster: (movie['poster_path'].blank? ? '' : 'http://image.tmdb.org/t/p/w500/' << movie['poster_path']),
      country: (movie['production_countries'].blank? ? nil : movie['production_countries'][0]['name']),
      language: movie['original_language'],
      studio: studio
      )

    return medium
  end

  def store_in_database(movie)
    movie_credits = TmdbApiService.call_movie_credits(movie['id'])
    studio = find_studio(movie)
    categories = find_categories(movie)
    actors = find_actors(movie_credits['cast'])
    directors = find_directors(movie_credits['crew'])

    medium = Medium.create(
      tmdbid: movie['id'].to_i,
      poster: (movie['poster_path'].blank? ? '' : 'http://image.tmdb.org/t/p/w500/' << movie['poster_path']),
      title: movie['title'],
      synopsys: movie['overview'],
      duration: movie['runtime'].to_i,
      year: (movie['release_date'].blank? ? '' : movie['release_date'].match(/\d{4}/)[0].to_i),
      country: (movie['production_countries'].blank? ? nil : movie['production_countries'][0]['name']),
      press_rating: movie['vote_average'].to_f, # TODO: use IMDB for rating
      audience_rating: movie['vote_average'].to_f,
      language: movie['original_language'],
      studio: studio
      )
    medium.categories = categories
    medium.actors = actors
    medium.directors = directors
    return medium
  end

  def find_studio(movie)
    unless movie['production_companies'].blank?
      studio = Studio.find_by(name: movie['production_companies'][0]['name'])
      studio = Studio.create(name: movie['production_companies'][0]['name']) if studio.nil?
    end
    return studio
  end

  def find_categories(movie)
    categories = []
    names = movie['genres'].map { |c| c['name'] }
    names.each do |name|
      category = Category.find_by(name: name)
      category = Category.create(name: name) if category.nil?
      categories << category
    end
    return categories
  end

  def find_actors(cast)
    actors = []
    cast = cast.map { |c| {name: c['name'], photo: c['profile_path']} }
    cast.each do |person|
      names = person[:name].split(' ')
      if names.length == 1
        names = [names.first, names.first]
      else
        if names.length > 2
          names = [names[0..-2].join(' '), names.last]
        end
      end

      first_name = names[0]
      last_name = names[1]

      actor = nil
      Actor.where(last_name: last_name).each do |actor_family|
        if actor_family.first_name == first_name
          actor = actor_family
          actor.update(photo: (person[:photo].blank? ? '' : 'http://image.tmdb.org/t/p/w500/' << person[:photo]))
        end
      end

      if actor.nil?
        actor = Actor.create(
          first_name: first_name,
          last_name: last_name,
          photo: (person[:photo].blank? ? '' : 'http://image.tmdb.org/t/p/w500/' << person[:photo])
          )
      end
      actors << actor
    end
    return actors
  end

  def find_directors(crew)
    directors = []
    crew = crew.map { |c| {name: c['name'], photo: c['profile_path']} if c['job'] == 'Director' }
    crew.compact.each do |person|

      names = person[:name].split(' ')
      if names.length == 1
        names = [names.first, names.first]
      else
        if names.length > 2
          names = [names[0..-2].join(' '), names.last]
        end
      end

      first_name = names[0]
      last_name = names[1]

      director = nil
      Director.where(last_name: last_name).each do |director_family|
        if director_family.first_name == first_name
          director = director_family
          director.update(photo: (person[:photo].blank? ? '' : 'http://image.tmdb.org/t/p/w500/' <<  person[:photo]))
        end
      end

      if director.nil?
        director = Director.create(
          first_name: first_name,
          last_name: last_name,
          photo: (person[:photo].blank? ? '' : 'http://image.tmdb.org/t/p/w500/' << person[:photo])
          )
      end
      directors << director
    end
    return directors
  end

  def advanced_search?
    unless params[:adv].nil?
      !(
        params[:adv][:c].blank? &&
        params[:adv][:mood].blank? &&
        params[:adv][:a].blank? &&
        params[:adv][:d].blank? &&
        params[:adv][:seen].nil? &&
        params[:adv][:recent].nil? &&
        params[:adv][:netflix].nil? &&
        params[:adv][:amazon].nil?
      ) # TODO : add rule for year and duration
    end
  end
end

app/views/media/index-old.html.erb
<div id="medium-id" hidden><%= session[:media][@nb] %></div>
<% if @nb > 0 %>
  <form action="<%= discover_path %>">
    <input type="text" id="back" name="nb" value="<%= @nb - 1 %>" hidden></input>
    <input type="submit" class="btn btn-lg btn-back" value="<<"></input>
  </form>
<% end %>
<% if @nb < session[:media].size - 1 %>
  <form action="<%= discover_path %>">
    <input type="text" id="next" name="nb" value="<%= @nb + 1 %>" hidden></input>
    <input type="submit" class="btn btn-lg btn-next" value=">>"></input>
  </form>
<% end %>

<div class="container">
  <div class="row">
    <div class="col-xs-12">
      <div class="text-center">
        <h1>
          <%= @medium.title %>
          <small><%= (@medium.duration / 60).to_s << 'h ' << (@medium.duration % 60).to_s << 'min'%></small>
        </h1>
      </div>
    </div>
  </div>
  <div class="video-header">
    <div class="row">
      <div class="col-xs-12">
        <div class="text-center">
          <div id="already_watched" class="btn btn-lg btn-danger">Already watched</div>
          <span class="spacer"></span>
          <div id="watch_later" class="btn btn-lg btn-danger">Watch later</div>
          <span class="spacer"></span>
          <div id="blacklist" class="btn btn-lg btn-danger">Blacklist</div>
        </div>
      </div>
    </div>
  </div>
  <div class="video-wrapper">
    <div class="embed-responsive embed-responsive-16by9">
      <% search = URI.escape(@medium.title.tr(' ', '+') << 'Trailer') %>
      <iframe src="https://www.youtube.com/embed?listType=search&list=<%= search %>;autoplay=0" frameborder="0"></iframe>
    </div>
  </div>
  <div class="row">
    <% audience_rating = (@medium.audience_rating / 2).round %>
    <% press_rating = (@medium.press_rating / 2).round %>
    <div class="col-xs-4">
      <div class="text-center">
        <h3>Audience</h3>
        <% 5.times do |i| %>
          <span class="glyphicon glyphicon-star <%= i < audience_rating ? 'on' : 'off' %>"></span>
        <% end %>
      </div>
    </div>
    <div class="col-xs-4">
      <div class="text-center">
        <h3>Press</h3>
        <% 5.times do |i| %>
          <span class="glyphicon glyphicon-star <%= i < audience_rating ? 'on' : 'off' %>"></span>
        <% end %>
      </div>
    </div>
    <div class="col-xs-4">
      <div class="text-center stream-links">
        <%= link_to @medium.netflix_link do %>
          <%= image_tag 'netflix_small.png', width: 80, height: 80 %>
        <% end %>
        <%= link_to @medium.amazon_link do %>
          <%= image_tag 'amazon_small.jpg', width: 80, height: 80 %>
        <% end %>
      </div>
    </div>
  </div>
</div>

<div class="wrapper">
  <div class="container">
    <div class="red-well wrapper-well">
      <div class="media">
        <div class="media-left media-middle">
          <%= image_tag (@medium.poster.nil? ? 'avatar-movie.jpg' : @medium.poster), width: 300, height: 450, class: 'media-object' %>
        </div>
        <div class="media-body media-middle">
          <h2 class="media-heading text-center"><%= @medium.title %></h2>
          <p class="wrapper-container"><%= @medium.synopsys %></p>
        </div>
      </div>
    </div>
  </div>
</div>
<div class="wrapper-container">
  <div class="row">
    <div class="col-xs-6">
      <div class="media">
        <div class="media-left media-middle">
          <strong>Actors</strong>
        </div>
        <div class="media-body media-middle">
          <div class="row">
            <% counter = 0 %>
            <% @medium.actors.reverse.each do |actor| %>
                <% unless counter >= 4 %>
                  <% counter += 1 %>
                  <div class="col-xs-3">
                    <div class="text-center">
                      <%= image_tag (actor.photo.blank? ? 'blank-avatar.png' : actor.photo), width: 80 %>
                      <p><%= actor.full_name %></p>
                    </div>
                  </div>
                <% end %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
    <div class="col-xs-6">
      <div class="media">
        <div class="media-left media-middle">
          <strong>Studio</strong>
        </div>
        <div class="media-body media-middle">
          <p><%= @medium.studio.name %></p>
        </div>
      </div>
    </div>
  </div>
</div>
<div class="wrapper-container">
  <div class="row">
    <div class="col-xs-6">
      <div class="row">
        <div class="media">
          <div class="media-left media-middle">
            <strong>Director</strong>
          </div>
          <div class="media-body media-middle">
            <div class="row">
              <% @medium.directors.reverse.each do |director| %>
              <div class="col-xs-3">
                <div class="text-center">
                  <%= image_tag (director.photo.blank? ? 'blank-avatar.png' : director.photo), width: 80 %>
                  <p><%= director.full_name %></p>
                </div>
              </div>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="col-xs-6">
      <div class="row">
        <div class="media">
          <div class="media-left media-middle">
            <strong>Country</strong>
          </div>
          <div class="media-body media-middle">
            <p><%= @medium.country %></p>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<div class="container">
  <div class="row">
    <div class="col-xs-10 col-xs-offset-1">
      <% @medium.reviews.each do |review| %>
        <%= render 'components/review', review: review %>
      <% end %>

      <% if user_signed_in? %>
        <h4>Add a review to the movie</h4>
        <%= simple_form_for [@medium, Review.new], method: :post do |f| %>
        <%= f.input :title %>
        <%= f.input :description, as: :text %>
        <%= f.submit value: 'Submit review', class: 'btn btn-info' %>
        <% end %>
      <% else %>
        <%= link_to 'Sign in to post a review', new_user_session_path, class: 'btn btn-info' %>
      <% end %>
    </div>
  </div>
</div>

app/views/media/index.html.erb
<div id="medium-id" hidden><%= @medium.id %></div>

<% if @nb > 0 %>
  <form action="<%= discover_path %>">
    <input type="text" id="back" name="nb" value="<%= @nb - 1 %>" hidden></input>
    <input type="submit" class="previous-button" value="<"></input>
  </form>
<% end %>
<% if @nb < @data.size - 1 %>
  <form action="<%= discover_path %>">
    <input type="text" id="next" name="nb" value="<%= @nb + 1 %>" hidden></input>
    <input type="submit" class="next-button" value=">"></input>
  </form>
<% end %>


<% video_id = TmdbApiService.find_trailer(@medium.tmdbid) %>

<div class="container movie-show">
  <div class="row h-full">
    <% search = URI.escape(@medium.title.tr(' ', '+') << 'Trailer') %>
    <div class="col-xs-12 col-md-7 h-full" style="background: url(<%= image_url("https://img.youtube.com/vi/#{video_id}/maxresdefault.jpg") %>) center; background-size: cover;">
      <div class="overlay"></div>

      <% if user_signed_in? %>
        <div class="video-header">
          <div class="row">
            <div class="col-xs-12">
              <div class="text-center">
                <%= link_to 'Already watched', medium_libraries_path(@medium.id, already_watched: true), method: :post, class: "account-action fa fa-glasses"  %>
                <%= link_to 'Watch later', medium_libraries_path(@medium.id, watch_later: true), method: :post, class: "account-action fa fa-hourglass"  %>
                <%= link_to 'Blacklist', medium_libraries_path(@medium.id, blacklist: true), method: :post, class: "account-action fa fa-times-circle"  %>
              </div>
            </div>
          </div>
        </div>
      <% end %>
      <div class="movie-preview">
        <div class="row">
          <div class="col-xs-12 col-md-8">
            <div class="youtube-player" data-id="<%= video_id %>"></div>
            <div class="ratings">
              <% audience_rating = (@medium.audience_rating / 2).round %>
              <% press_rating = (@medium.press_rating / 2).round %>

              <div class="rating">
                <div class="title">AUDIENCE</div>
                <div class="stars">
                  <% 5.times do |i| %>
                    <span class="glyphicon glyphicon-star <%= i < audience_rating ? 'on' : 'off' %>"></span>
                  <% end %>
                </div>
              </div>

              <div class="rating">
                <div class="title">PRESS</div>
                <div class="stars">
                  <% 5.times do |i| %>
                    <span class="glyphicon glyphicon-star <%= i < press_rating ? 'on' : 'off' %>"></span>
                  <% end %>
                </div>
              </div>
            </div>
          </div>
        </div>

        <div class="row">
          <div class="col-xs-12 col-md-11">
            <p class="synopsis"><%= @medium.synopsys %></p>
          </div>
        </div>
      </div>
    </div>

    <div class="col-xs-12 col-sm-5">
      <div class="movie-details">
        <h2>
          <%= @medium.title %>
        </h2>
        <i class="fa fa-stopwatch">&nbsp;<%= (@medium.duration / 60).to_s << 'h ' << (@medium.duration % 60).to_s << 'min'%></i>
        <div class="movie-attributes">
          <%= image_tag (@medium.poster.nil? ? 'avatar-movie.jpg' : @medium.poster) %>

          <ul class="attributes-list">
            <li class="attribute">
              <div class="key">Direction:</div>
              <% @medium.directors.each do |director| %>
                <div class="value"><%= director.full_name %></div>
              <% end %>
            </li>
            <li class="attribute">
              <div class="key">Studio:</div>
              <div class="value"><%= @medium.studio.name %></div>
            </li>
            <li class="attribute">
              <div class="key">Genre(s):</div>
              <div class="value"><%= @medium.categories.map(&:name).join(', ') %></div>
            </li>
          </ul>
        </div>

        <div class="cast">
          <%# <h3>CAST</h3> %>

          <div class="actors">
            <% @medium.actors.each do |actor| %>
              <div class="actor">
                <%= image_tag (actor.photo.blank? ? 'blank-avatar.png' : actor.photo) %>
                <div class="name">
                  <%= actor.full_name %>
                </div>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>